/**
 * Fungsi untuk menghitung dan menghasilkan hasil tes STIFIn lengkap
 * berdasarkan tanggal lahir
 */
export default function getStifin(dateOfBirth: string) {
  // Bersihkan input dari karakter non-digit
  const digits = dateOfBirth.replace(/\D/g, "");

  // Jika tidak ada digit, return default
  if (!digits) {
    return {
      original: dateOfBirth,
      digits: "",
      result: 0,
      stifinType: null,
      typeName: null,
      description: null,
      characteristics: [],
      suitableCareers: [],
      learningStyle: null,
      communicationStyle: null,
      strengths: [],
      weaknesses: [],
      tips: [],
      metadata: {
        calculatedAt: new Date().toISOString(),
        method: "STIFIn Numerological Reduction",
      },
    };
  }

  // Hitung digital root (reduksi numerologi)
  let sum = digits
    .split("")
    .reduce((total, char) => total + Number(char), 0);

  while (sum >= 10) {
    sum = sum
      .toString()
      .split("")
      .reduce((total, char) => total + Number(char), 0);
  }

  // Mapping hasil ke tipe STIFIn (berdasarkan rumus yang benar)
  const stifinTypes = {
    1: {
      type: "Ti",
      name: "Thinking Introvert",
      description: "Tipe Thinking Introvert adalah individu yang analitis, logis, dan cenderung introspektif. Mereka membuat keputusan berdasarkan prinsip dan logika, serta lebih nyaman bekerja sendiri.",
      characteristics: [
        "Analitis dan logis",
        "Introspektif dan reflektif",
        "Berpikir sebelum bertindak",
        "Menyukai kebenaran dan keadilan",
        "Kritis terhadap diri sendiri dan orang lain",
        "Fokus pada ide dan konsep",
        "Menyelesaikan masalah dengan pendekatan sistematis",
        "Menghargai kompetensi dan keahlian",
      ],
      suitableCareers: [
        "Analis sistem",
        "Programmer",
        "Akuntan",
        "Ilmuwan/peneliti",
        "Insinyur",
        "Ahli strategi",
        "Konsultan IT",
        "Penulis teknis",
        "Arsitek",
        "Analis data",
      ],
      learningStyle: "Belajar melalui analisis mendalam, membaca, dan penelitian mandiri. Menyukai teori dan konsep yang terstruktur.",
      communicationStyle: "Komunikasi yang terukur, terstruktur, dan faktual. Cenderung langsung ke pokok pembahasan dan menghindari basa-basi.",
      strengths: [
        "Analitis dan objektif",
        "Teliti dan sistematis",
        "Mampu konsentrasi tinggi",
        "Mandiri dan dapat diandalkan",
        "Pemikir kritis yang baik",
        "Pandai memecahkan masalah kompleks",
      ],
      weaknesses: [
        "Bisa terlalu kritis dan perfeksionis",
        "Kurang peka terhadap perasaan orang lain",
        "Sulit beradaptasi dengan perubahan",
        "Cenderung menarik diri dari interaksi sosial",
        "Terlalu keras pada diri sendiri",
      ],
      tips: [
        "Seimbangkan logika dengan empati",
        "Latih komunikasi interpersonal",
        "Berikan apresiasi pada diri sendiri",
        "Coba untuk lebih terbuka terhadap perspektif orang lain",
      ],
    },
    2: {
      type: "Fe",
      name: "Feeling Ekstrovert",
      description: "Tipe Feeling Ekstrovert adalah individu yang hangat, empatik, dan energik. Mereka membuat keputusan berdasarkan nilai-nilai dan perasaan, serta mendapatkan energi dari interaksi sosial.",
      characteristics: [
        "Empatik dan peduli",
        "Sosial dan ramah",
        "Ekspresif dan emosional",
        "Menyukai harmoni",
        "Peka terhadap perasaan orang lain",
        "Mendapat energi dari interaksi",
        "Mudah bergaul dan membangun relasi",
        "Diplomatis dalam komunikasi",
      ],
      suitableCareers: [
        "Konselor/psikolog",
        "Guru/dosen",
        "Pekerja sosial",
        "HRD/Manager SDM",
        "Marketing/Public Relations",
        "Event organizer",
        "Sales profesional",
        "Pelatih/coach",
        "Terapis",
        "Customer service",
      ],
      learningStyle: "Belajar melalui interaksi sosial, diskusi kelompok, dan aplikasi praktis yang berdampak pada orang lain.",
      communicationStyle: "Komunikasi hangat, persuasif, dan emosional. Menyukai interaksi personal dan membangun koneksi.",
      strengths: [
        "Empatik dan penyayang",
        "Pandai membangun hubungan",
        "Energik dan memotivasi",
        "Diplomatis dan bijaksana",
        "Mudah beradaptasi dengan orang lain",
        "Komunikator yang baik",
      ],
      weaknesses: [
        "Terlalu emosional dalam keputusan",
        "Sulit mengatakan 'tidak'",
        "Bergantung pada validasi sosial",
        "Bisa terlalu mengorbankan diri",
        "Kurang objektif",
      ],
      tips: [
        "Seimbangkan emosi dengan logika",
        "Pelajari untuk menetapkan batasan",
        "Latih pengambilan keputusan yang objektif",
        "Berikan waktu untuk refleksi diri",
      ],
    },
    3: {
      type: "Si",
      name: "Sensing Introvert",
      description: "Tipe Sensing Introvert adalah individu yang detail-oriented, praktis, dan reflektif. Mereka fokus pada fakta dan pengalaman nyata, serta lebih nyaman dalam kesendirian.",
      characteristics: [
        "Teliti dan detail-oriented",
        "Praktis dan realistik",
        "Reflektif dan introspektif",
        "Mengandalkan pengalaman masa lalu",
        "Terorganisir dan terstruktur",
        "Menyukai rutinitas",
        "Memori yang baik untuk detail",
        "Observasional dan waspada",
      ],
      suitableCareers: [
        "Akuntan",
        "Arsitek",
        "Ahli forensik",
        "Teknisi",
        "Analis keuangan",
        "Peneliti lapangan",
        "Dokter spesialis",
        "Quality control",
        "Insinyur",
        "Ahli konservasi",
      ],
      learningStyle: "Belajar melalui pengalaman langsung, demonstrasi, dan praktik yang terstruktur. Menyukai instruksi yang jelas dan bertahap.",
      communicationStyle: "Komunikasi yang terukur, spesifik, dan berbasis fakta. Cenderung menghindari pembicaraan yang terlalu abstrak.",
      strengths: [
        "Teliti dan akurat",
        "Konsisten dan dapat diandalkan",
        "Praktis dan efisien",
        "Pandai mengorganisir",
        "Fokus dan disiplin",
        "Observasional yang baik",
      ],
      weaknesses: [
        "Terlalu kaku dan sulit beradaptasi",
        "Kurang visioner",
        "Terlalu fokus pada detail",
        "Sulit menerima perubahan",
        "Kurang spontanitas",
      ],
      tips: [
        "Coba lihat gambaran besar sesekali",
        "Terima perubahan sebagai bagian dari proses",
        "Beri ruang untuk kreativitas",
        "Kerjasama dengan tipe Intuiting",
      ],
    },
    4: {
      type: "Se",
      name: "Sensing Ekstrovert",
      description: "Tipe Sensing Ekstrovert adalah individu yang praktis, energik, dan action-oriented. Mereka belajar melalui pengalaman langsung dan mendapatkan energi dari aktivitas dan interaksi.",
      characteristics: [
        "Praktis dan realistis",
        "Energik dan aktif",
        "Orientasi pada tindakan",
        "Menikmati pengalaman langsung",
        "Sosial dan ramah",
        "Responsif terhadap lingkungan",
        "Suka petualangan dan aktivitas fisik",
        "Pandai dalam krisis",
      ],
      suitableCareers: [
        "Atlet/profesi olahraga",
        "Teknisi lapangan",
        "Pilot",
        "Koki/chef",
        "Polisi/tentara",
        "Paramudik",
        "Sales lapangan",
        "Event organizer",
        "Fotografer",
        "Real estate agent",
      ],
      learningStyle: "Belajar melalui pengalaman langsung, praktik, dan interaksi fisik dengan lingkungan. Menyukai pembelajaran yang dinamis dan seru.",
      communicationStyle: "Komunikasi langsung, ekspresif, dan bersemangat. Menyukai interaksi yang aktif dan penuh energi.",
      strengths: [
        "Praktis dan efisien",
        "Energik dan bersemangat",
        "Mudah beradaptasi",
        "Pandai menghadapi situasi darurat",
        "Proaktif dan inisiatif",
        "Menyenangkan dan karismatik",
      ],
      weaknesses: [
        "Kurang sabar",
        "Cenderung impulsif",
        "Kurang suka perencanaan detail",
        "Bisa mengabaikan konsekuensi jangka panjang",
        "Sulit fokus pada satu hal",
      ],
      tips: [
        "Seimbangkan aksi dengan perencanaan",
        "Latih kesabaran dan refleksi",
        "Pikirkan konsekuensi jangka panjang",
        "Buat ruang untuk istirahat dan kontemplasi",
      ],
    },
    5: {
      type: "Fi",
      name: "Feeling Introvert",
      description: "Tipe Feeling Introvert adalah individu yang mendalam, sensitif, dan berprinsip. Mereka sangat menghargai nilai-nilai personal dan memiliki dunia emosi yang kaya di dalam diri.",
      characteristics: [
        "Autentik dan berprinsip",
        "Empatik dan sensitif",
        "Reflektif dan introspektif",
        "Menghargai keunikan",
        "Memiliki nilai-nilai kuat",
        "Kreatif dan ekspresif",
        "Peduli terhadap kesejahteraan orang lain",
        "Menyukai hubungan yang mendalam",
      ],
      suitableCareers: [
        "Konselor/psikolog",
        "Penulis/kreator konten",
        "Seniman/musisi",
        "Guru",
        "Pekerja sosial",
        "Terapis",
        "Konsultan HR",
        "Pemimpin organisasi sosial",
        "Pelatih pengembangan diri",
        "Spiritual counselor",
      ],
      learningStyle: "Belajar melalui refleksi personal, nilai-nilai, dan aplikasi yang bermakna. Menyukai pembelajaran yang berhubungan dengan pengalaman pribadi.",
      communicationStyle: "Komunikasi yang dalam, personal, dan autentik. Menghargai percakapan yang bermakna dan hubungan satu-satu.",
      strengths: [
        "Autentik dan jujur",
        "Empatik dan peduli",
        "Kreatif dan ekspresif",
        "Berprinsip kuat",
        "Mendengarkan dengan baik",
        "Membuat hubungan yang mendalam",
      ],
      weaknesses: [
        "Terlalu sensitif terhadap kritik",
        "Sulit memisahkan perasaan pribadi",
        "Bisa terlalu menyendiri",
        "Kurang asertif",
        "Cenderung menyembunyikan perasaan",
      ],
      tips: [
        "Nyatakan perasaan dengan jujur",
        "Latih asertivitas dan batasan",
        "Jangan terlalu keras pada diri sendiri",
        "Seimbangkan dunia internal dan eksternal",
      ],
    },
    6: {
      type: "Ie",
      name: "Intuiting Ekstrovert",
      description: "Tipe Intuiting Ekstrovert adalah individu yang visioner, inovatif, dan energik. Mereka melihat kemungkinan masa depan dan mendapatkan energi dari berbagi ide dengan orang lain.",
      characteristics: [
        "Visioner dan inovatif",
        "Energik dan antusias",
        "Sosial dan komunikatif",
        "Berorientasi pada masa depan",
        "Kreatif dan imajinatif",
        "Inspiratif dan persuasif",
        "Mudah bergaul dengan berbagai orang",
        "Cepat memahami konsep baru",
      ],
      suitableCareers: [
        "Inovator/entrepreneur",
        "Konsultan strategi",
        "Pembawa acara/motivator",
        "Pengembang produk",
        "Marketing strategis",
        "Desainer",
        "Penulis/filmmaker",
        "Pemimpin organisasi",
        "Kreator konten",
        "Ahli futuristik",
      ],
      learningStyle: "Belajar melalui brainstorming, diskusi, dan eksplorasi ide. Menyukai pembelajaran yang dinamis dan kolaboratif.",
      communicationStyle: "Komunikasi yang inspiratif, bersemangat, dan visioner. Menyukai diskusi ide besar dan membagikan antusiasme.",
      strengths: [
        "Kreatif dan inovatif",
        "Energik dan memotivasi",
        "Pandai berkomunikasi",
        "Melihat peluang dan potensi",
        "Inspiratif dan persuasif",
        "Mudah beradaptasi",
      ],
      weaknesses: [
        "Kurang sabar dengan detail",
        "Cenderung terlalu optimis",
        "Sulit fokus pada satu proyek",
        "Bisa mengabaikan realitas",
        "Kurang praktis dalam eksekusi",
      ],
      tips: [
        "Seimbangkan ide dengan eksekusi",
        "Kerjasama dengan tipe Sensing",
        "Buat rencana aksi yang konkret",
        "Pelajari untuk mengelola detail",
      ],
    },
    7: {
      type: "Ii",
      name: "Intuiting Introvert",
      description: "Tipe Intuiting Introvert adalah individu yang introspektif, visioner, dan kreatif. Mereka memiliki dunia imajinasi yang kaya dan fokus pada ide-ide besar serta kemungkinan masa depan.",
      characteristics: [
        "Introspektif dan reflektif",
        "Visioner dan imajinatif",
        "Kreatif dan inovatif",
        "Berpikir konseptual",
        "Menyukai teori dan abstraksi",
        "Melihat pola dan hubungan",
        "Berorientasi pada masa depan",
        "Menyukai kesendirian untuk merenung",
      ],
      suitableCareers: [
        "Peneliti akademik",
        "Inovator/R&D",
        "Filosof",
        "Penulis novelis",
        "Arsitek",
        "Ahli strategi",
        "Ilmuwan",
        "Desainer konseptual",
        "Pengembang AI",
        "Konsultan inovasi",
      ],
      learningStyle: "Belajar melalui refleksi mendalam, membaca, dan eksplorasi konsep teoritis. Menyukai pembelajaran yang menantang imajinasi.",
      communicationStyle: "Komunikasi yang konseptual dan reflektif. Menyukai percakapan yang dalam dan bermakna tentang ide-ide besar.",
      strengths: [
        "Kreatif dan inovatif",
        "Pandai melihat gambaran besar",
        "Analitis dan konseptual",
        "Mandiri dan fokus",
        "Pemikir strategis",
        "Imajinatif dan orisinal",
      ],
      weaknesses: [
        "Terlalu idealis dan abstrak",
        "Sulit berkomunikasi dengan tipe praktis",
        "Cenderung menyendiri",
        "Kurang praktis",
        "Bisa kehilangan kontak dengan realitas",
      ],
      tips: [
        "Seimbangkan ide dengan tindakan",
        "Coba untuk lebih berbagi ide dengan orang lain",
        "Terapkan ide dalam bentuk praktis",
        "Bergaul dengan tipe Sensing untuk keseimbangan",
      ],
    },
    8: {
      type: "Te",
      name: "Thinking Ekstrovert",
      description: "Tipe Thinking Ekstrovert adalah individu yang objektif, tegas, dan proaktif. Mereka membuat keputusan berdasarkan logika dan fakta, serta aktif dalam memimpin dan mengorganisir.",
      characteristics: [
        "Objektif dan logis",
        "Tegas dan decisif",
        "Proaktif dan energik",
        "Berorientasi pada hasil",
        "Pemimpin alami",
        "Sistematis dan terorganisir",
        "Kritis dan analitis",
        "Komunikatif dan persuasif",
      ],
      suitableCareers: [
        "Manajer/eksekutif",
        "Pengacara",
        "Analis keuangan",
        "Konsultan manajemen",
        "Pemimpin militer",
        "Entrepreneur",
        "Pengembang bisnis",
        "Quality assurance",
        "Manajer proyek",
        "Direktur operasional",
      ],
      learningStyle: "Belajar melalui sistem, struktur, dan aplikasi praktis. Menyukai pembelajaran yang terorganisir dan berorientasi tujuan.",
      communicationStyle: "Komunikasi tegas, langsung, dan berorientasi pada hasil. Menyukai debat dan diskusi yang konstruktif.",
      strengths: [
        "Objektif dan rasional",
        "Tegas dan cepat mengambil keputusan",
        "Pemimpin yang efektif",
        "Sistematis dan terorganisir",
        "Kritis dan analitis",
        "Pandai mengelola tim",
      ],
      weaknesses: [
        "Bisa terlalu otoriter",
        "Kurang peka terhadap perasaan",
        "Terlalu fokus pada hasil",
        "Cenderung memaksakan kehendak",
        "Kurang fleksibel",
      ],
      tips: [
        "Berikan perhatian pada perasaan tim",
        "Latih empati dan kesabaran",
        "Seimbangkan tugas dengan hubungan",
        "Terima masukan dan kritik dengan terbuka",
      ],
    },
    9: {
      type: "In",
      name: "Insting",
      description: "Tipe Insting adalah individu yang unik dan intuitif, menggabungkan kebijaksanaan dengan kepekaan alamiah. Mereka memiliki 'sixth sense' yang kuat dan sering bertindak berdasarkan firasat.",
      characteristics: [
        "Intuitif dan perseptif",
        "Memiliki insting yang kuat",
        "Bijaksana dan matang",
        "Autentik dan original",
        "Melihat esensi dari hal-hal",
        "Menyeluruh dan holistik",
        "Menggabungkan logika dan perasaan",
        "Pandai membaca situasi",
      ],
      suitableCareers: [
        "Mentor/coach",
        "Konsultan senior",
        "Pemimpin visioner",
        "Ahli strategi",
        "Psikolog",
        "Filosof",
        "Penasihat spiritual",
        "Detektif/analis kriminal",
        "Ahli medis holistik",
        "Kreator konten inspiratif",
      ],
      learningStyle: "Belajar melalui pengalaman hidup, refleksi mendalam, dan intuisi. Menyukai pembelajaran yang bermakna dan transformatif.",
      communicationStyle: "Komunikasi yang bijaksana, mendalam, dan penuh makna. Mampu menyampaikan pesan dengan cara yang menginspirasi.",
      strengths: [
        "Intuitif dan perseptif",
        "Bijaksana dan dewasa",
        "Autentik dan original",
        "Melihat gambaran menyeluruh",
        "Pandai memecahkan masalah kompleks",
        "Menginspirasi orang lain",
      ],
      weaknesses: [
        "Sulit menjelaskan intuisi pada orang lain",
        "Bisa terlalu idealis",
        "Terkadang sulit diterima karena unik",
        "Kurang terstruktur",
        "Bisa disalahpahami",
      ],
      tips: [
        "Percayai insting Anda",
        "Latih komunikasi untuk menjelaskan intuisi",
        "Seimbangkan intuisi dengan logika",
        "Cari lingkungan yang menghargai keunikan Anda",
      ],
    },
  };

  // Ambil data tipe berdasarkan hasil
  const typeData = stifinTypes[sum as keyof typeof stifinTypes] || null;

  // Generate metadata
  const metadata = {
    calculatedAt: new Date().toISOString(),
    method: "STIFIn Numerological Reduction",
    birthDate: dateOfBirth,
    digitSum: digits,
    reductionResult: sum,
  };

  // Return hasil lengkap
  return {
    original: dateOfBirth,
    digits: digits,
    result: sum,
    stifinType: typeData?.type || null,
    typeName: typeData?.name || null,
    description: typeData?.description || null,
    characteristics: typeData?.characteristics || [],
    suitableCareers: typeData?.suitableCareers || [],
    learningStyle: typeData?.learningStyle || null,
    communicationStyle: typeData?.communicationStyle || null,
    strengths: typeData?.strengths || [],
    weaknesses: typeData?.weaknesses || [],
    tips: typeData?.tips || [],
    metadata: metadata,
  };
}